// -----------------
// <auto-generated/>
// -----------------

#nullable disable
namespace ManagedLzma.LZMA.Master;

using System;

internal static partial class LZMA {
    /* #define SHOW_STAT */
    /* #define SHOW_STAT2 */
    /* #define SHOW_DEBUG_INFO */
    /* #define PROTOTYPE */

    [System.Diagnostics.Conditional("BUILD_TESTING")]
    [System.Diagnostics.Conditional("SHOW_DEBUG_INFO")]
    internal static void DebugPrint(string format, params object[] args) {
        System.Diagnostics.Debug.Write(String.Format(format, args));
    }

    [System.Diagnostics.Conditional("BUILD_TESTING")]
    internal static void Print(string format, params object[] args) {
        System.Diagnostics.Debug.Write(String.Format(format, args));
    }
}
