// -----------------
// <auto-generated/>
// -----------------

#nullable enable
namespace pdj.tiny7z.Archive;

using System;

public class SevenZipException : Exception {
    internal SevenZipException(string message) : base(message) { }
    internal SevenZipException(string? message, Exception? innerException) : base(message, innerException) { }
}

public class SevenZipFileAlreadyExistsException : SevenZipException {
    internal SevenZipFileAlreadyExistsException(SevenZipArchiveFile file) : this(file, null) { }
    internal SevenZipFileAlreadyExistsException(SevenZipArchiveFile file, Exception? innerException) : base($"File `{file.Name}` already exists.", innerException) { }
}

public class SevenZipPasswordRequiredException : SevenZipException {
    internal SevenZipPasswordRequiredException() : this(null) { }
    internal SevenZipPasswordRequiredException(Exception? innerException) : base("No password provided. Encrypted stream requires password.", innerException) { }
}
