// -----------------
// <auto-generated/>
// -----------------

#nullable disable
namespace pdj.tiny7z.Archive;

using System;
using System.IO;

/// <summary>
/// Represents one file in an archive
/// </summary>
public class ArchiveFile {
    public string EntryName {
        get {
            return Path.GetFileName(this.Name);
        }
    }
    public string Name { get; set; }
    public UInt64? Size { get; set; }
    public UInt32? CRC { get; set; }
    public DateTime? Time { get; set; }
    public UInt32? Attributes { get; set; }
    public bool IsEmpty { get; set; }
    public bool IsDirectory { get; set; }
    public bool IsDeleted { get; set; }
    public ArchiveFile() {
        Name = null;
        Size = null;
        CRC = null;
        Time = null;
        Attributes = null;
        IsEmpty = false;
        IsDirectory = false;
        IsDeleted = false;
    }
}
