//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------

namespace System.Windows.Forms;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
// System.Windows.Forms.ClientUtils
internal static class ClientUtils {
    public static bool IsEnumValid(Enum enumValue, int value, int minValue, int maxValue) {
        return value >= minValue && value <= maxValue;
    }
}
#endif
