//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------

namespace System.Windows.Forms;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
// System.Windows.Forms.Command
internal class Command : IDisposable {
    private static readonly Type CommandType = typeof(Control).Assembly.GetType(typeof(Command).FullName);
    private static readonly Reflection.PropertyInfo CommandIDProperty = CommandType.GetProperty(nameof(ID), typeof(Int32));
    private static readonly Reflection.MethodInfo CommandDisposeMethod = CommandType.GetMethod(nameof(Dispose), Type.EmptyTypes);

    private readonly Object cmd;

    public Int32 ID {
        get {
            return (Int32)CommandIDProperty.GetValue(this.cmd);
        }
    }

    public Command(ICommandExecutor target) {
        this.cmd = Activator.CreateInstance(CommandType, target);
    }

    public void Dispose() {
        CommandDisposeMethod.Invoke(this.cmd, null);
    }
}
#endif
