//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------

namespace System.Windows.Forms.Natives;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
using System.Runtime.InteropServices;
using System.Security;

[SuppressUnmanagedCodeSecurity]
// System.Windows.Forms.SafeNativeMethods
internal static class SafeNativeMethods {
    [DllImport("gdi32.dll", CharSet = CharSet.Auto, EntryPoint = "DeleteObject", ExactSpelling = true, SetLastError = true)]
    internal static extern bool IntDeleteObject(HandleRef hObject);

    public static bool DeleteObject(HandleRef hObject) {
        System.Internal.HandleCollector.Remove((IntPtr)hObject, NativeMethods.CommonHandles.GDI);
        return IntDeleteObject(hObject);
    }

    [DllImport("user32.dll", CharSet = CharSet.Auto, ExactSpelling = true)] // NativeMethods.TPMPARAMS
    public static extern bool TrackPopupMenuEx(HandleRef hmenu, int fuFlags, int x, int y, HandleRef hwnd, int tpm);

    [DllImport("gdi32.dll", CharSet = CharSet.Auto, ExactSpelling = true, SetLastError = true)]
    public static extern IntPtr SelectPalette(HandleRef hdc, HandleRef hpal, int bForceBackground);

    [DllImport("gdi32.dll", CharSet = CharSet.Auto, ExactSpelling = true, SetLastError = true)]
    public static extern int RealizePalette(HandleRef hDC);

    [DllImport("user32.dll", CharSet = CharSet.Auto, ExactSpelling = true)]
    public static extern bool DrawMenuBar(HandleRef hWnd);

    [DllImport("comctl32.dll")]
    public static extern bool InitCommonControlsEx(NativeMethods.INITCOMMONCONTROLSEX icc);

    [DllImport("user32.dll", CharSet = CharSet.Auto, ExactSpelling = true)]
    public static extern bool SetWindowPos(HandleRef hWnd, HandleRef hWndInsertAfter, int x, int y, int cx, int cy, int flags);
}
#endif
