//----------------------
// <auto-generated>
//     Backwards compatibility with StatusBars.
// </auto-generated>
//----------------------

#nullable enable
namespace System.Windows.Forms;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
/// <summary>
///     Specifies how a panel on a status bar changes when the
///     status bar resizes.
/// </summary>
internal enum StatusBarPanelAutoSize {
    /// <summary>
    ///     The panel does not change
    ///     its size when the status bar resizes.
    /// </summary>
    None = 1,
    /// <summary>
    ///     The panel shares the available status bar space (the
    ///     space not taken up by panels with the <see langword='None'/> and
    ///     <see langword='Contents'/> settings) with other panels that have the
    ///     <see langword='Spring'/>
    ///     setting.
    /// </summary>
    Spring = 2,
    /// <summary>
    ///     The width of the panel is determined by its contents.
    /// </summary>
    Contents = 3,
}
#endif
