//----------------------
// <auto-generated>
//     Backwards compatibility with StatusBars.
// </auto-generated>
//----------------------

#nullable enable
namespace System.Windows.Forms;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
using System.Drawing;

/// <summary>
///     Provides data for the <see cref='StatusBar.OnDrawItem'/> event.
/// </summary>
internal class StatusBarDrawItemEventArgs : DrawItemEventArgs {
    /// <summary>
    ///     Initializes a new instance of the <see cref='StatusBarDrawItemEventArgs'/> class.
    /// </summary>
    public StatusBarDrawItemEventArgs(Graphics g, Font font, Rectangle r, int itemId,
        DrawItemState itemState, StatusBarPanel panel) : base(g, font, r, itemId, itemState) {
        this.Panel = panel;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref='StatusBarDrawItemEventArgs'/> class using the Forecolor and Backcolor.
    /// </summary>
    public StatusBarDrawItemEventArgs(Graphics g, Font font, Rectangle r, int itemId,
        DrawItemState itemState, StatusBarPanel panel, Color foreColor, Color backColor) : base(g, font, r, itemId, itemState, foreColor, backColor) {
        this.Panel = panel;
    }

    /// <summary>
    ///     Specifies the <see cref='StatusBarPanel'/> to draw.
    /// </summary>
    public StatusBarPanel Panel { get; }
}
#endif
