//----------------------
// <auto-generated>
//     Backwards compatibility with StatusBars.
// </auto-generated>
//----------------------

#nullable enable
namespace System.Windows.Forms;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
/// <summary>
///     Specifies the border style of a panel on the <see cref='StatusBar'/>.
/// </summary>
internal enum StatusBarPanelBorderStyle {
    /// <summary>
    ///     No border.
    /// </summary>
    None = 1,
    /// <summary>
    ///     A raised border.
    /// </summary>
    Raised = 2,
    /// <summary>
    ///     A sunken border.
    /// </summary>
    Sunken = 3,
}
#endif
