//----------------------
// <auto-generated>
//     Backwards compatibility with StatusBars.
// </auto-generated>
//----------------------

#nullable enable
namespace System.Windows.Forms;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
/// <summary>
///     Specifies whether a panel on a status bar is owner drawn or system drawn.
/// </summary>
internal enum StatusBarPanelStyle {
    /// <summary>
    ///     The panel is drawn by the system.
    /// </summary>
    Text = 1,
    /// <summary>
    ///     The panel is drawn by the owner.
    /// </summary>
    OwnerDraw = 2,
}
#endif
