//----------------------
// <auto-generated>
//     Backwards compatibility with Menus.
// </auto-generated>
//----------------------

namespace System.Internal;

#if NETCOREAPP3_1_OR_GREATER && ENABLE_LEGACY_MENUS
// System.Internal.HandleChangeEventHandler
internal delegate void HandleChangeEventHandler(string handleType, IntPtr handleValue, int currentHandleCount);
#endif
