// <auto-generated/>
namespace DOOMer.Controls;

using System.Runtime.InteropServices;

internal struct TV_ITEM {
    public uint mask;
    public nint hItem;
    public uint state;
    public uint stateMask;
    [MarshalAs(UnmanagedType.LPTStr)]
    public string pszText;
    public int cchTextMax;
    public int iImage;
    public int iSelectedImage;
    public int cChildren;
    public nint lParam;
}
